/*
	Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
	Triangle   --> Tn=n(n+1)/2  --> 1, 3, 6, 10, 15, ...
	Pentagonal --> Pn=n(3n−1)/2 --> 1, 5, 12, 22, 35, ...
	Hexagonal  --> Hn=n(2n−1)   --> 1, 6, 15, 28, 45, ...

	It can be verified that T285 = P165 = H143 = 40755.

	Find the next triangle number that is also pentagonal and hexagonal.
*/

function isPentagonNumber(x) {
	return (1 + Math.sqrt(1 + 24 * x)) % 6 === 0;
}

function isTriangleNumber(x) {
	return (Math.sqrt(8 * x + 1) - 1) % 2 === 0;
}

function triPentaHexa(n) {
	let i = 144;
	let prev = n;
	const nextHexagonal = x => x * (2 * x - 1);
	while (!isPentagonNumber(prev) || !isTriangleNumber(prev)) {
		prev = nextHexagonal(i);
		i += 1;
	}

	return prev;
}

console.log(triPentaHexa(40756));
